format_version: v1.0
type: GroupComponent
attributes: {displayName: BASIC CONFIGURATION, id: BASIC CONFIGURATION}
children:
- type: ElementPosition
  attributes: {x: '242', y: '162', id: BASIC CONFIGURATION}
- type: Attachments
  children:
  - type: Attachment
    attributes: {namespace: tcpipNetConfig_0, id: NETCONFIG_MAC_Dependency}
  - type: Attachment
    attributes: {namespace: tcpipStack, id: Core_SysConsole_Dependency}
  - type: Attachment
    attributes: {namespace: tcpipStack, id: Core_SysConsole_Dependency}
  - type: Attachment
    attributes: {namespace: tcpipStack, id: Core_SysConsole_Dependency}
